config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :competence
  root to: 'competences#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/author.rb
class Author < ApplicationRecord
  has_one :user
 has_many :competences
end

app/models/competence.rb
class Competence < ApplicationRecord
  VALID_REGEXP = /\A[a-zA-Z\s]+\z/i
  VALID_REGEXP_SKILL = /\A[1-3]\z/i
  validates :title, presence: true, format: { with: VALID_REGEXP }
  validates :skillrate, format: { with: VALID_REGEXP_SKILL }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :email, presence: true
  validates :password, length: 6..20

 has_many :authors

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/competence_controller.rb
class CompetenceController < ApplicationController
  before_action :set_competence, only: [:show, :update, :edit, :destroy]
  def index
    @competences = Competence.all
  end
  def show
  end

  def new
    @competence = Competence.new
  end

  def create
    @competence = Competence.new
    respond_to do |f|
      if @competence.save (competence_params)
        f.html {redirect_to @competence}
      else
        f.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |f|
      if @competence.update (competence_params)
        f.html {redirect_to @competence}
      else
        f.html {render :edit}

      end
    end
  end

  def destroy
    if @competence.destroy
      respond_to do |f|
        f.html {redirect_to competences_url}
      end
    end
  end
  private
  def set_competence
    @competence = Competence.find (params[:id])
  end
  def competence_params
    params.require (:competence).permit (:title, :author, :skillrate)
  end
end

app/controllers/competences_controller.rb
class CompetenceController < ApplicationController
  before_action :set_competence, only: [:show, :update, :edit, :destroy]
  def index
    @competences = Competence.all
  end
  def show
  end

  def new
    @competence = Competence.new
  end

  def create
    @competence = Competence.new
    respond_to do |f|
      if @competence.save (competence_params)
        f.html {redirect_to @competence}
      else
        f.html {render :new}
      end
    end
  end

  def edit
  end

  def update
    respond_to do |f|
      if @competence.update (competence_params)
        f.html {redirect_to @competence}
      else
        f.html {render :edit}

      end
    end
  end

  def destroy
    if @competence.destroy
      respond_to do |f|
        f.html {redirect_to competences_url}
      end
    end
  end

  private
  def set_competence
    @competence = Competence.find (params[:id])
  end
  def competence_params
    params.require(:competence).permit(:title, :author, :skillrate)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/competence_helper.rb
module CompetenceHelper
end

app/views/competence/_form.html.haml
= simple_form_for(competence) do |f|
  = f.error_notification
    .form-inputs
      = f.input :title
      = f.input :author
      = f.input :skillrate
    .form.actions
      =f.button :submit

app/views/competence/edit.html.haml
= render 'form', competence: @competence

app/views/competence/index.html.haml
%h1 Компетенции
  %table.table.table-hover
    %thead
      %tr.panel.panel-heading
        %th Название
        %th Авторj
        %th Уровень владения (от 1 до 3)
  %tbody
    - @competences.each do |x|
      %tr
        %td= x.title
        %td= x.author
        %td= x.skillrate
        %td= link_to ' Показать '
        %td= link_to 'Редактировать ]'
        %td= link_to 'Удалить'

app/views/competence/new.html.haml
= render 'form', competence: @competence
= link_to 'Back', competence_path

app/views/competence/show.html.haml
%p = @competence.title
%p = @competence.author
%p = @competence.skillrate
= link_to 'Edit', edit_competence_path(@competence)
= link_to 'Back', competence_path

app/views/layouts/application.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

<!DOCTYPE html>
<html>
  <head>
    <title>Profport</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>